name: smart_accounting
description: AI-powered expense tracking app built with Flutter
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI Components
  cupertino_icons: ^1.0.2
  
  # State Management
  provider: ^6.0.5
  
  # HTTP & API
  http: ^1.1.0
  
  # Local Storage
  shared_preferences: ^2.2.0
  
  # Image and Camera
  image_picker: ^1.0.4
  
  # Audio and Speech
  speech_to_text: ^6.3.0
  permission_handler: ^11.0.1
  
  # Utils
  uuid: ^4.0.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true