name: Build Flutter APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        channel: 'stable'
        cache: true
        
    - name: Get dependencies
      run: |
        cd flutter_app
        flutter pub get
        
    - name: Generate files
      run: |
        cd flutter_app
        flutter pub run build_runner build --delete-conflicting-outputs || true
        
    - name: Build APK
      run: |
        cd flutter_app
        flutter build apk --release
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: flutter_app/build/app/outputs/flutter-apk/app-release.apk
        
    - name: Create Release
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      with:
        files: flutter_app/build/app/outputs/flutter-apk/app-release.apk
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        body: |
          Automatically generated release from GitHub Actions
          - Build number: ${{ github.run_number }}
          - Commit: ${{ github.sha }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}